---

- name: git clone|pull pyenv repo
  git:
    repo: https://github.com/yyuu/pyenv.git
    dest: "{{user_home}}/.pyenv"
    update: yes

- name: install multiple plugins from yyuu for pyenv
  git:
    repo: "https://github.com/yyuu/{{item}}.git"
    dest: "{{user_home}}/.pyenv/plugins/{{item}}"
    update: yes
  with_items:
    - pyenv-doctor
    - pyenv-pip-rehash
    - pyenv-update
    - pyenv-virtualenv
    - pyenv-which-ext

- name: set-up pyenv init file
  copy: src=pyenv-init.sh dest={{user_home}}/.pyenv-init.sh
