---

- include: apt.yml
  when: ansible_pkg_mgr == 'apt'
- include: homebrew.yml
  when: ansible_os_family == 'Darwin'
  become: true

- include: base.yml
  become: true

- set_fact:
    role_javascript_done: true
