---

# add a tmux.conf
- name: settings tmux.conf
  copy: src=tmux.conf dest={{user_home}}/.tmux.conf

- name: set-up autojump init file
  copy: src=autojump-init.sh dest={{user_home}}/.autojump-init.sh
