---

- name: install some small, awesome packages to boost your life
  homebrew: name={{item}} state=present
  with_items:
    - ag
    - cloc
    - editorconfig
    - global
    - htop-osx
    - md5sha1sum
    - mosh
    - ranger
    - reattach-to-user-namespace
    - rlwrap
    - ssh-copy-id
    - texinfo
    - tig
    - tmux
    - wget
